name: Code changes

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          enable-cache: true

      - name: Install shfmt and shellcheck
        run: |
          sudo apt-get install -y shfmt shellcheck

      - name: Run ansible-lint
        working-directory: bootstrap
        run: uvx --with-requirements=requirements_dev.txt ansible-lint setup.yml
      
      - name: Run shellcheck
        run: shellcheck bootstrap.bash

      - name: Run shfmt
        run: shfmt -l -d -i 4 bootstrap.bash

      - name: Run j2lint
        run: uvx --with-requirements=bootstrap/requirements_dev.txt j2lint templates
