name: Code changes

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Code quality
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true

      - name: Run ansible-lint
        working-directory: bootstrap
        run: uvx --with-requirements=requirements_dev.txt ansible-lint setup.yml
      
      - name: Run shellcheck
        run: shellcheck bootstrap.bash

      - name: Run shfmt
        run: shfmt -l -d -i 4 bootstrap.bash

      - name: Run j2lint
        run: uvx --with-requirements=bootstrap/requirements_dev.txt j2lint templates
